Import necessary library. Make sure you are running your google colab using GPU

In [1]:
import os
import json
import argparse
import time
import numpy as np
import pandas as pd
import datetime
import tensorflow as tf
import time
from pickle import TRUE
from tensorflow.keras import layers
from keras.models import load_model
from sklearn import utils
from tqdm import tqdm as tqdm
from sklearn import metrics 
import warnings
warnings.filterwarnings('ignore')

print("GPU Condition", tf.test.is_gpu_available()) # True/False

WARNING:tensorflow:From <ipython-input-1-bd0ec7314e16>:19: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
GPU Condition True

# **Next Activity Prediction Task**

# Preprocessing Part
Upload necessary dataset to your directory. We are using Helpdesk dataset as example.
*   **Make sure the dataset has columns name Case ID, Activity, Complete Timestamp, and Resource (If not, please rename it manually)**

You can download our sample dataset here (https://drive.google.com/drive/folders/1x2en9pUz1ak8IO_6ocE-hpkGylaz1da3?usp=sharing)

In [2]:
#change to your prefered event log
df = pd.read_csv("Helpdesk.csv")

In [3]:
df

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,Variant.1,seriousness,customer,product,responsible_section,seriousness_2,service_level,service_type,support_section,workgroup
0,Case 1,Assign seriousness,Value 1,2012/10/09 14:50:17.000,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1
1,Case 1,Take in charge ticket,Value 1,2012/10/09 14:51:01.000,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1
2,Case 1,Take in charge ticket,Value 2,2012/10/12 15:02:56.000,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1
3,Case 1,Resolve ticket,Value 1,2012/10/25 11:54:26.000,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1
4,Case 1,Closed,Value 3,2012/11/09 12:54:39.000,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21343,Case 4579,Closed,Value 5,2010/09/02 10:11:00.000,Variant 1,1,Variant 1,Value 1,Value 71,Value 3,Value 1,Value 1,Value 3,Value 1,Value 1,Value 1
21344,Case 4580,Take in charge ticket,Value 6,2012/01/03 09:33:43.000,Variant 18,18,Variant 18,Value 1,Value 92,Value 3,Value 1,Value 2,Value 2,Value 2,Value 1,Value 1
21345,Case 4580,Wait,Value 6,2012/01/10 15:30:11.000,Variant 18,18,Variant 18,Value 1,Value 92,Value 3,Value 1,Value 2,Value 2,Value 2,Value 1,Value 1
21346,Case 4580,Resolve ticket,Value 6,2012/01/10 17:07:40.000,Variant 18,18,Variant 18,Value 1,Value 92,Value 3,Value 1,Value 2,Value 2,Value 2,Value 1,Value 1
21347,Case 4580,Closed,Value 5,2012/02/08 17:00:34.000,Variant 18,18,Variant 18,Value 1,Value 92,Value 3,Value 1,Value 2,Value 2,Value 2,Value 1,Value 1

In [4]:
df = df[['Case ID', 'Activity', 'Complete Timestamp', 'Resource']]
df.columns = ["Case", "Activity", "Timestamp", 'Resource']

In [5]:
df

            Case               Activity                Timestamp Resource
0         Case 1     Assign seriousness  2012/10/09 14:50:17.000  Value 1
1         Case 1  Take in charge ticket  2012/10/09 14:51:01.000  Value 1
2         Case 1  Take in charge ticket  2012/10/12 15:02:56.000  Value 2
3         Case 1         Resolve ticket  2012/10/25 11:54:26.000  Value 1
4         Case 1                 Closed  2012/11/09 12:54:39.000  Value 3
...          ...                    ...                      ...      ...
21343  Case 4579                 Closed  2010/09/02 10:11:00.000  Value 5
21344  Case 4580  Take in charge ticket  2012/01/03 09:33:43.000  Value 6
21345  Case 4580                   Wait  2012/01/10 15:30:11.000  Value 6
21346  Case 4580         Resolve ticket  2012/01/10 17:07:40.000  Value 6
21347  Case 4580                 Closed  2012/02/08 17:00:34.000  Value 5

[21348 rows x 4 columns]

In [6]:
df["Activity"] = df["Activity"].str.lower()
df["Activity"] = df["Activity"].str.replace(" ", "-")

df["Timestamp"] = df["Timestamp"].str.replace("/", "-")
df["Timestamp"]= pd.to_datetime(df["Timestamp"], dayfirst=True).map(lambda x: x.strftime("%Y-%m-%d %H:%M:%S"))

In [7]:
df

            Case               Activity            Timestamp Resource
0         Case 1     assign-seriousness  2012-10-09 14:50:17  Value 1
1         Case 1  take-in-charge-ticket  2012-10-09 14:51:01  Value 1
2         Case 1  take-in-charge-ticket  2012-10-12 15:02:56  Value 2
3         Case 1         resolve-ticket  2012-10-25 11:54:26  Value 1
4         Case 1                 closed  2012-11-09 12:54:39  Value 3
...          ...                    ...                  ...      ...
21343  Case 4579                 closed  2010-09-02 10:11:00  Value 5
21344  Case 4580  take-in-charge-ticket  2012-01-03 09:33:43  Value 6
21345  Case 4580                   wait  2012-01-10 15:30:11  Value 6
21346  Case 4580         resolve-ticket  2012-01-10 17:07:40  Value 6
21347  Case 4580                 closed  2012-02-08 17:00:34  Value 5

[21348 rows x 4 columns]

In [8]:
keys = ["[PAD]", "[UNK]"]
activities = list(df["Activity"].unique())
resources = list(df["Resource"].unique())
resources = list(map(str, resources))

keys.extend(activities)
val = range(len(keys))

coded_activity = dict({"x_word_dict":dict(zip(keys, val))})
code_activity_normal = dict({"y_word_dict": dict(zip(activities, range(len(activities))))})
code_resource_normal = dict({"x2_word_dict": dict(zip(resources, range(len(resources))))})

coded_activity.update(code_activity_normal)
coded_activity.update(code_resource_normal)

coded_json = json.dumps(coded_activity)
with open(f"metadata.json", "w") as metadata_file:
    metadata_file.write(coded_json)

In [9]:
train_test_ratio = int(abs(df["Case"].nunique()*0.80))
train_list = df["Case"].unique()[:train_test_ratio]
test_list = df["Case"].unique()[train_test_ratio:]

In [10]:
case_id = "Case"
case_name = "Activity"
case_resource = "Resource"

processed_df = pd.DataFrame(columns = ["case_id", "resource", "prefix", "k", "next_act"])
idx = 0
unique_cases = df[case_id].unique()

for _, case in enumerate(tqdm(unique_cases)):
    act = df[df[case_id] == case][case_name].to_list()
    resource = df[df[case_id] == case][case_resource].to_list()
    for i in range(len(act) - 1):
        prefix = np.where(i == 0, act[0], " ".join(act[:i+1]))
        next_act = act[i+1]
        resource_act = resource[i]

        processed_df.at[idx, "case_id"] = case
        processed_df.at[idx, "resource"] = resource_act
        processed_df.at[idx, "prefix"] = prefix
        processed_df.at[idx, "k"] = i
        processed_df.at[idx, "next_act"] = next_act
        idx = idx + 1

100%|██████████| 4580/4580 [00:59<00:00, 77.44it/s]

In [11]:
train_remaining_time = processed_df[processed_df["case_id"].isin(train_list)]
test_remaining_time = processed_df[processed_df["case_id"].isin(test_list)]
train_remaining_time.to_csv(f"train.csv", index = False)
test_remaining_time.to_csv(f"test.csv", index = False)

# Proposal Architecture (Transformer + Resource Embedding)

In [12]:
class TokenResourceAndPositionEmbedding(layers.Layer):
    def __init__(self, maxlen, resource_size, vocab_size, embed_dim):
        super(TokenResourceAndPositionEmbedding, self).__init__()
        self.token_emb = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)
        self.res_emb = layers.Embedding(input_dim=resource_size, output_dim=embed_dim)
        self.pos_emb = layers.Embedding(input_dim=maxlen, output_dim=embed_dim)

    def call(self, x, x2):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        x2 = self.res_emb(x2)
        return x + x2 + positions 

class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = tf.keras.Sequential(
            [layers.Dense(ff_dim, activation="relu"), layers.Dense(embed_dim),]
        )
        self.layernorm_a = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm_b = layers.LayerNormalization(epsilon=1e-6)
        self.dropout_a = layers.Dropout(rate)
        self.dropout_b = layers.Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout_a(attn_output, training=training)
        out_a = self.layernorm_a(inputs + attn_output)
        ffn_output = self.ffn(out_a)
        ffn_output = self.dropout_b(ffn_output, training=training)
        return self.layernorm_b(out_a + ffn_output)

#For transfer learning purpose
def set_trainable(model, transfer_criteria = 'finetune_all', print_details = True):
    # freeze layer 0 to layer l, and unfreeze layer l+1 up until layer L
    #freeze all layers
    if transfer_criteria == 'freeze_all':
        for layer in model.layers:
            layer.trainable = False

    #finetune all layers
    elif transfer_criteria == 'finetune_all':
        for layer in model.layers:
            layer.trainable = True

    #set layers trainable from the specified layer up to the last layer
    else:
        trainable_condition = True
        for layer in model.layers:
            trainable_condition = True
            if layer.name == "transformer_block":
                trainable_condition = False
            layer.trainable = trainable_condition

# Next Activity Model

In [13]:
def get_next_activity_model(max_case_length, vocab_size, resource_size, output_dim, base_model_path, transfer_learning, 
    embed_dim = 34, num_heads = 4, ff_dim = 64):

    x_inputs = layers.Input(shape=(max_case_length,))
    x2_inputs = layers.Input(shape=(max_case_length))
    x = TokenResourceAndPositionEmbedding(max_case_length, resource_size, vocab_size, embed_dim)(x_inputs, x2_inputs)
    x = TransformerBlock(embed_dim, num_heads, ff_dim)(x)
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dropout(0.1)(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(0.1)(x)
    outputs = layers.Dense(output_dim, activation="linear")(x)
    if(transfer_learning):
      transformer = tf.keras.Model(inputs=[x_inputs,x2_inputs], outputs=outputs, name = "next_activity_transformer_transfer_learning")
      model_trained = load_model(base_model_path)
      for a in range(8):
          if a == 2 or a == 8:
              continue
          extracted_weights = model_trained.layers[a].get_weights()
          transformer.layers[a].set_weights(extracted_weights)
      
      set_trainable(transformer, transfer_criteria="transformer_block", print_details=False)
    else:
      transformer = tf.keras.Model(inputs=[x_inputs,x2_inputs], outputs=outputs, name = "next_activity_transformer")
    
    print("model", transformer.summary())
    return transformer

# Next Activity Data Loader

In [14]:
def prepare_data_next_activity(df, 
        x_word_dict, y_word_dict, x2_word_dict, 
        max_case_length, shuffle=False):

        x = df["prefix"].values
        y = df["next_act"].values
        x2 = df["resource"].values
        if shuffle:
            x, y, x2 = utils.shuffle(x, y, x2)

        token_x = list()
        
        for _x in x:
            token_x.append([x_word_dict[s] for s in _x.split()])

        token_y = list()
        for _y in y:
            token_y.append(y_word_dict[_y])

        token_x2 = list()
        for _x2 in x2:
            token_x2.append(x2_word_dict[str(_x2)])

        token_x = tf.keras.preprocessing.sequence.pad_sequences(
            token_x, maxlen=max_case_length)

        token_x2_final = np.zeros(token_x.shape)
        for idx, x in enumerate(token_x2):
            token_x2_final[idx, :] = x

        token_x2 = token_x2_final
        token_x = np.array(token_x, dtype=np.float32)
        token_y = np.array(token_y, dtype=np.float32)
        token_x2 = np.array(token_x2, dtype=np.float32)

        return token_x, token_y, token_x2

def get_max_case_length(train_x):
        train_token_x = list()
        for _x in train_x:
            train_token_x.append(len(_x.split()))
        return max(train_token_x)

def load_data():
        train_df = pd.read_csv(f"train.csv")
        test_df = pd.read_csv(f"test.csv")

        with open(f"metadata.json", "r") as json_file:
            metadata = json.load(json_file)

        x_word_dict = metadata["x_word_dict"]
        y_word_dict = metadata["y_word_dict"]
        x2_word_dict = metadata["x2_word_dict"]
        max_case_length = get_max_case_length(train_df["prefix"].values)
        vocab_size = len(x_word_dict) 
        resource_size = len(x2_word_dict)
        total_classes = len(y_word_dict)

        return (train_df, test_df, 
            x_word_dict, y_word_dict, x2_word_dict,
            max_case_length, vocab_size, resource_size,
            total_classes)

# Training

In [15]:
(train_df, test_df, x_word_dict, y_word_dict, x2_word_dict, max_case_length, vocab_size, resource_size, num_output) = load_data()
train_token_x, train_token_y, token_x2 = prepare_data_next_activity(train_df, x_word_dict, y_word_dict, x2_word_dict, max_case_length)

In [16]:
transformer_resource_embedding_model = get_next_activity_model(
        max_case_length=max_case_length, 
        vocab_size=vocab_size,
        resource_size=resource_size,
        output_dim=num_output,
        base_model_path=None,
        transfer_learning=False)

Model: "next_activity_transformer"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_1 (InputLayer)           [(None, 14)]         0           []

 input_2 (InputLayer)           [(None, 14)]         0           []

 token_resource_and_position_em  (None, 14, 34)      1768        ['input_1[0][0]',
 bedding (TokenResourceAndPosit                                   'input_2[0][0]']
 ionEmbedding)

 transformer_block (Transformer  (None, 14, 34)      23524       ['token_resource_and_position_emb
 Block)                                                          edding[0][0]']

 global_average_pooling1d (Glob  (None, 34)          0           ['transformer_block[0][0]']
 alAveragePooling1D)

 dropout_2 (Dropout)            (None, 34)           0           ['global_average_pooling1d[0][0]'
                                                                 ]

 dense_2 (Dense)                (None, 64)           2240        ['dropout_2[0][0]']

 dropout_3 (Dropout)            (None, 64)           0           ['dense_2[0][0]']

 dense_3 (Dense)                (None, 14)           910         ['dropout_3[0][0]']

==================================================================================================
Total params: 28,442
Trainable params: 28,442
Non-trainable params: 0
__________________________________________________________________________________________________
model None

In [17]:
transformer_resource_embedding_model.compile(optimizer=tf.keras.optimizers.Adam(0.001), 
                          loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                          metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

In [18]:
transformer_resource_embedding_model.fit([train_token_x, token_x2], train_token_y, 
                      epochs=50, batch_size=256, 
                      shuffle=True, verbose=2)

Epoch 1/50
53/53 - 3s - loss: 1.6437 - sparse_categorical_accuracy: 0.3676 - 3s/epoch - 49ms/step
Epoch 2/50
53/53 - 0s - loss: 1.0459 - sparse_categorical_accuracy: 0.6819 - 384ms/epoch - 7ms/step
Epoch 3/50
53/53 - 0s - loss: 0.7906 - sparse_categorical_accuracy: 0.7664 - 376ms/epoch - 7ms/step
Epoch 4/50
53/53 - 0s - loss: 0.7034 - sparse_categorical_accuracy: 0.7820 - 360ms/epoch - 7ms/step
Epoch 5/50
53/53 - 0s - loss: 0.6774 - sparse_categorical_accuracy: 0.7858 - 364ms/epoch - 7ms/step
Epoch 6/50
53/53 - 0s - loss: 0.6578 - sparse_categorical_accuracy: 0.7879 - 361ms/epoch - 7ms/step
Epoch 7/50
53/53 - 0s - loss: 0.6478 - sparse_categorical_accuracy: 0.7932 - 381ms/epoch - 7ms/step
Epoch 8/50
53/53 - 0s - loss: 0.6341 - sparse_categorical_accuracy: 0.7960 - 374ms/epoch - 7ms/step
Epoch 9/50
53/53 - 0s - loss: 0.6303 - sparse_categorical_accuracy: 0.7963 - 358ms/epoch - 7ms/step
Epoch 10/50
53/53 - 0s - loss: 0.6241 - sparse_categorical_accuracy: 0.7960 - 363ms/epoch - 7ms/step
Epoch 11/50
53/53 - 0s - loss: 0.6167 - sparse_categorical_accuracy: 0.7977 - 354ms/epoch - 7ms/step
Epoch 12/50
53/53 - 0s - loss: 0.6153 - sparse_categorical_accuracy: 0.7966 - 364ms/epoch - 7ms/step
Epoch 13/50
53/53 - 0s - loss: 0.6152 - sparse_categorical_accuracy: 0.7986 - 370ms/epoch - 7ms/step
Epoch 14/50
53/53 - 0s - loss: 0.6120 - sparse_categorical_accuracy: 0.7983 - 361ms/epoch - 7ms/step
Epoch 15/50
53/53 - 0s - loss: 0.6100 - sparse_categorical_accuracy: 0.7989 - 365ms/epoch - 7ms/step
Epoch 16/50
53/53 - 0s - loss: 0.6119 - sparse_categorical_accuracy: 0.7987 - 368ms/epoch - 7ms/step
Epoch 17/50
53/53 - 0s - loss: 0.6056 - sparse_categorical_accuracy: 0.7987 - 359ms/epoch - 7ms/step
Epoch 18/50
53/53 - 0s - loss: 0.6056 - sparse_categorical_accuracy: 0.7983 - 368ms/epoch - 7ms/step
Epoch 19/50
53/53 - 0s - loss: 0.6019 - sparse_categorical_accuracy: 0.7992 - 363ms/epoch - 7ms/step
Epoch 20/50
53/53 - 0s - loss: 0.6004 - sparse_categorical_accuracy: 0.7998 - 362ms/epoch - 7ms/step
Epoch 21/50
53/53 - 0s - loss: 0.5990 - sparse_categorical_accuracy: 0.7980 - 370ms/epoch - 7ms/step
Epoch 22/50
53/53 - 0s - loss: 0.6010 - sparse_categorical_accuracy: 0.8000 - 369ms/epoch - 7ms/step
Epoch 23/50
53/53 - 0s - loss: 0.6012 - sparse_categorical_accuracy: 0.8007 - 359ms/epoch - 7ms/step
Epoch 24/50
53/53 - 0s - loss: 0.5960 - sparse_categorical_accuracy: 0.7996 - 372ms/epoch - 7ms/step
Epoch 25/50
53/53 - 0s - loss: 0.5964 - sparse_categorical_accuracy: 0.7989 - 378ms/epoch - 7ms/step
Epoch 26/50
53/53 - 0s - loss: 0.5952 - sparse_categorical_accuracy: 0.8001 - 361ms/epoch - 7ms/step
Epoch 27/50
53/53 - 0s - loss: 0.5930 - sparse_categorical_accuracy: 0.7994 - 361ms/epoch - 7ms/step
Epoch 28/50
53/53 - 0s - loss: 0.5970 - sparse_categorical_accuracy: 0.7989 - 358ms/epoch - 7ms/step
Epoch 29/50
53/53 - 0s - loss: 0.5941 - sparse_categorical_accuracy: 0.7995 - 384ms/epoch - 7ms/step
Epoch 30/50
53/53 - 0s - loss: 0.5928 - sparse_categorical_accuracy: 0.8006 - 350ms/epoch - 7ms/step
Epoch 31/50
53/53 - 0s - loss: 0.5900 - sparse_categorical_accuracy: 0.8003 - 357ms/epoch - 7ms/step
Epoch 32/50
53/53 - 0s - loss: 0.5912 - sparse_categorical_accuracy: 0.8012 - 363ms/epoch - 7ms/step
Epoch 33/50
53/53 - 0s - loss: 0.5924 - sparse_categorical_accuracy: 0.7993 - 357ms/epoch - 7ms/step
Epoch 34/50
53/53 - 0s - loss: 0.5907 - sparse_categorical_accuracy: 0.8017 - 353ms/epoch - 7ms/step
Epoch 35/50
53/53 - 0s - loss: 0.5891 - sparse_categorical_accuracy: 0.8018 - 361ms/epoch - 7ms/step
Epoch 36/50
53/53 - 0s - loss: 0.5886 - sparse_categorical_accuracy: 0.8015 - 359ms/epoch - 7ms/step
Epoch 37/50
53/53 - 0s - loss: 0.5877 - sparse_categorical_accuracy: 0.7992 - 355ms/epoch - 7ms/step
Epoch 38/50
53/53 - 0s - loss: 0.5871 - sparse_categorical_accuracy: 0.8017 - 371ms/epoch - 7ms/step
Epoch 39/50
53/53 - 0s - loss: 0.5873 - sparse_categorical_accuracy: 0.8016 - 356ms/epoch - 7ms/step
Epoch 40/50
53/53 - 0s - loss: 0.5883 - sparse_categorical_accuracy: 0.7993 - 359ms/epoch - 7ms/step
Epoch 41/50
53/53 - 0s - loss: 0.5865 - sparse_categorical_accuracy: 0.8025 - 372ms/epoch - 7ms/step
Epoch 42/50
53/53 - 0s - loss: 0.5836 - sparse_categorical_accuracy: 0.7992 - 356ms/epoch - 7ms/step
Epoch 43/50
53/53 - 0s - loss: 0.5865 - sparse_categorical_accuracy: 0.8009 - 371ms/epoch - 7ms/step
Epoch 44/50
53/53 - 0s - loss: 0.5847 - sparse_categorical_accuracy: 0.8006 - 353ms/epoch - 7ms/step
Epoch 45/50
53/53 - 0s - loss: 0.5825 - sparse_categorical_accuracy: 0.8008 - 354ms/epoch - 7ms/step
Epoch 46/50
53/53 - 0s - loss: 0.5797 - sparse_categorical_accuracy: 0.8020 - 363ms/epoch - 7ms/step
Epoch 47/50
53/53 - 0s - loss: 0.5833 - sparse_categorical_accuracy: 0.8018 - 355ms/epoch - 7ms/step
Epoch 48/50
53/53 - 0s - loss: 0.5816 - sparse_categorical_accuracy: 0.8027 - 356ms/epoch - 7ms/step
Epoch 49/50
53/53 - 0s - loss: 0.5819 - sparse_categorical_accuracy: 0.8019 - 362ms/epoch - 7ms/step
Epoch 50/50
53/53 - 0s - loss: 0.5826 - sparse_categorical_accuracy: 0.8022 - 359ms/epoch - 7ms/step

# Evaluate Model

In [19]:
k, accuracies,fscores, precisions, recalls = [],[],[],[],[]
for i in range(max_case_length):
    test_data_subset = test_df[test_df["k"]==i]
    if len(test_data_subset) > 0:
        test_token_x, test_token_y, token_x2 = prepare_data_next_activity(test_data_subset, 
            x_word_dict, y_word_dict, x2_word_dict, max_case_length)   
        y_pred = np.argmax(transformer_resource_embedding_model.predict([test_token_x, token_x2]), axis=1)
        accuracy = metrics.accuracy_score(test_token_y, y_pred)
        precision, recall, fscore, _ = metrics.precision_recall_fscore_support(
            test_token_y, y_pred, average="weighted")
        k.append(i)
        accuracies.append(accuracy)
        fscores.append(fscore)
        precisions.append(precision)
        recalls.append(recall)

k.append(i + 1)
accuracies.append(np.mean(accuracy))
fscores.append(np.mean(fscores))
precisions.append(np.mean(precisions))
recalls.append(np.mean(recalls))
print('Average accuracy across all prefixes:', np.mean(accuracies))
print('Average f-score across all prefixes:', np.mean(fscores))
print('Average precision across all prefixes:', np.mean(precisions))
print('Average recall across all prefixes:', np.mean(recalls))

Average accuracy across all prefixes: 0.8580184801833283
Average f-score across all prefixes: 0.8158421873801773
Average precision across all prefixes: 0.8362523405500755
Average recall across all prefixes: 0.8461866868652722

# Transfer Learning

Now, lets implement Transfer Learning
*   You can train any dataset and save the model using above code and use that model as base model for transfer learning
*   Or you can download our BPIC2012 Prediction Model as base model in here (https://drive.google.com/drive/folders/1oER0QlOVHy_dgys3YCmqNx9Q6HLNxGT9?usp=sharing)

**Download whole folder as zip and upload to your directory**

In [27]:
#remove our current transformer model
tf.keras.backend.clear_session()

In [28]:
#your zipped file name
if os.path.exists("BPIC2012"):
  !rm -rf BPIC2012
!unzip BPIC2012_Base_Model.zip

Archive:  BPIC2012_Base_Model.zip
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/remaining_time_ckpt/keras_metadata.pb
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/remaining_time_ckpt/saved_model.pb
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/checkpoint
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/remaining_time_ckpt.data-00000-of-00001
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_activity_ckpt.index
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_activity_ckpt/saved_model.pb
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_activity_ckpt/keras_metadata.pb
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_time_ckpt/saved_model.pb
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_time_ckpt/variables/variables.index
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_time_ckpt/variables/variables.data-00000-of-00001
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/remaining_time_ckpt/variables/variables.index
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/remaining_time_ckpt/variables/variables.data-00000-of-00001
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_time_ckpt/keras_metadata.pb
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_activity_ckpt/variables/variables.index
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_activity_ckpt/variables/variables.data-00000-of-00001
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/next_activity_ckpt.data-00000-of-00001
  inflating: BPIC2012/transfer_learning_base_BPIC_2012/remaining_time_ckpt.index

#Training

In [29]:
(train_df, test_df, x_word_dict, y_word_dict, x2_word_dict, max_case_length, vocab_size, resource_size, num_output) = load_data()
train_token_x, train_token_y, token_x2 = prepare_data_next_activity(train_df, x_word_dict, y_word_dict, x2_word_dict, max_case_length)

In [30]:
transformer_resource_embedding_and_transfer_learning_model = get_next_activity_model(
        max_case_length=max_case_length, 
        vocab_size=vocab_size,
        resource_size=resource_size,
        output_dim=num_output,
        base_model_path="BPIC2012/transfer_learning_base_BPIC_2012/next_activity_ckpt",
        transfer_learning=True)

Model: "next_activity_transformer_transfer_learning"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_1 (InputLayer)           [(None, 14)]         0           []

 input_2 (InputLayer)           [(None, 14)]         0           []

 token_resource_and_position_em  (None, 14, 34)      1768        ['input_1[0][0]',
 bedding (TokenResourceAndPosit                                   'input_2[0][0]']
 ionEmbedding)

 transformer_block (Transformer  (None, 14, 34)      23524       ['token_resource_and_position_emb
 Block)                                                          edding[0][0]']

 global_average_pooling1d (Glob  (None, 34)          0           ['transformer_block[0][0]']
 alAveragePooling1D)

 dropout_2 (Dropout)            (None, 34)           0           ['global_average_pooling1d[0][0]'
                                                                 ]

 dense_2 (Dense)                (None, 64)           2240        ['dropout_2[0][0]']

 dropout_3 (Dropout)            (None, 64)           0           ['dense_2[0][0]']

 dense_3 (Dense)                (None, 14)           910         ['dropout_3[0][0]']

==================================================================================================
Total params: 28,442
Trainable params: 4,918
Non-trainable params: 23,524
__________________________________________________________________________________________________
model None

In [31]:
transformer_resource_embedding_and_transfer_learning_model.compile(optimizer=tf.keras.optimizers.Adam(0.001), 
                          loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                          metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

In [32]:
transformer_resource_embedding_and_transfer_learning_model.fit([train_token_x, token_x2], train_token_y, epochs=50, batch_size=256, shuffle=True, verbose=2)

Epoch 1/50
53/53 - 2s - loss: 2.2061 - sparse_categorical_accuracy: 0.2448 - 2s/epoch - 30ms/step
Epoch 2/50
53/53 - 0s - loss: 1.2478 - sparse_categorical_accuracy: 0.5664 - 366ms/epoch - 7ms/step
Epoch 3/50
53/53 - 0s - loss: 0.8460 - sparse_categorical_accuracy: 0.7502 - 357ms/epoch - 7ms/step
Epoch 4/50
53/53 - 0s - loss: 0.7525 - sparse_categorical_accuracy: 0.7670 - 329ms/epoch - 6ms/step
Epoch 5/50
53/53 - 0s - loss: 0.7110 - sparse_categorical_accuracy: 0.7789 - 333ms/epoch - 6ms/step
Epoch 6/50
53/53 - 0s - loss: 0.6874 - sparse_categorical_accuracy: 0.7861 - 330ms/epoch - 6ms/step
Epoch 7/50
53/53 - 0s - loss: 0.6764 - sparse_categorical_accuracy: 0.7886 - 328ms/epoch - 6ms/step
Epoch 8/50
53/53 - 0s - loss: 0.6626 - sparse_categorical_accuracy: 0.7918 - 345ms/epoch - 7ms/step
Epoch 9/50
53/53 - 0s - loss: 0.6492 - sparse_categorical_accuracy: 0.7919 - 322ms/epoch - 6ms/step
Epoch 10/50
53/53 - 0s - loss: 0.6457 - sparse_categorical_accuracy: 0.7942 - 338ms/epoch - 6ms/step
Epoch 11/50
53/53 - 0s - loss: 0.6381 - sparse_categorical_accuracy: 0.7945 - 342ms/epoch - 6ms/step
Epoch 12/50
53/53 - 0s - loss: 0.6352 - sparse_categorical_accuracy: 0.7950 - 333ms/epoch - 6ms/step
Epoch 13/50
53/53 - 0s - loss: 0.6314 - sparse_categorical_accuracy: 0.7959 - 341ms/epoch - 6ms/step
Epoch 14/50
53/53 - 0s - loss: 0.6307 - sparse_categorical_accuracy: 0.7951 - 344ms/epoch - 6ms/step
Epoch 15/50
53/53 - 0s - loss: 0.6239 - sparse_categorical_accuracy: 0.7972 - 333ms/epoch - 6ms/step
Epoch 16/50
53/53 - 0s - loss: 0.6207 - sparse_categorical_accuracy: 0.7963 - 326ms/epoch - 6ms/step
Epoch 17/50
53/53 - 0s - loss: 0.6220 - sparse_categorical_accuracy: 0.7986 - 332ms/epoch - 6ms/step
Epoch 18/50
53/53 - 0s - loss: 0.6163 - sparse_categorical_accuracy: 0.7988 - 324ms/epoch - 6ms/step
Epoch 19/50
53/53 - 0s - loss: 0.6143 - sparse_categorical_accuracy: 0.7991 - 327ms/epoch - 6ms/step
Epoch 20/50
53/53 - 0s - loss: 0.6102 - sparse_categorical_accuracy: 0.7980 - 339ms/epoch - 6ms/step
Epoch 21/50
53/53 - 0s - loss: 0.6109 - sparse_categorical_accuracy: 0.7975 - 336ms/epoch - 6ms/step
Epoch 22/50
53/53 - 0s - loss: 0.6079 - sparse_categorical_accuracy: 0.7972 - 328ms/epoch - 6ms/step
Epoch 23/50
53/53 - 0s - loss: 0.6098 - sparse_categorical_accuracy: 0.8006 - 335ms/epoch - 6ms/step
Epoch 24/50
53/53 - 0s - loss: 0.6062 - sparse_categorical_accuracy: 0.7999 - 332ms/epoch - 6ms/step
Epoch 25/50
53/53 - 0s - loss: 0.6098 - sparse_categorical_accuracy: 0.7993 - 338ms/epoch - 6ms/step
Epoch 26/50
53/53 - 0s - loss: 0.6079 - sparse_categorical_accuracy: 0.8000 - 345ms/epoch - 7ms/step
Epoch 27/50
53/53 - 0s - loss: 0.6043 - sparse_categorical_accuracy: 0.8000 - 326ms/epoch - 6ms/step
Epoch 28/50
53/53 - 0s - loss: 0.6026 - sparse_categorical_accuracy: 0.7997 - 338ms/epoch - 6ms/step
Epoch 29/50
53/53 - 0s - loss: 0.6055 - sparse_categorical_accuracy: 0.7987 - 335ms/epoch - 6ms/step
Epoch 30/50
53/53 - 0s - loss: 0.6021 - sparse_categorical_accuracy: 0.8015 - 329ms/epoch - 6ms/step
Epoch 31/50
53/53 - 0s - loss: 0.6028 - sparse_categorical_accuracy: 0.8016 - 343ms/epoch - 6ms/step
Epoch 32/50
53/53 - 0s - loss: 0.5984 - sparse_categorical_accuracy: 0.7992 - 345ms/epoch - 7ms/step
Epoch 33/50
53/53 - 0s - loss: 0.5987 - sparse_categorical_accuracy: 0.8003 - 338ms/epoch - 6ms/step
Epoch 34/50
53/53 - 0s - loss: 0.5977 - sparse_categorical_accuracy: 0.8012 - 349ms/epoch - 7ms/step
Epoch 35/50
53/53 - 0s - loss: 0.5979 - sparse_categorical_accuracy: 0.7997 - 329ms/epoch - 6ms/step
Epoch 36/50
53/53 - 0s - loss: 0.5961 - sparse_categorical_accuracy: 0.8004 - 327ms/epoch - 6ms/step
Epoch 37/50
53/53 - 0s - loss: 0.5950 - sparse_categorical_accuracy: 0.8020 - 340ms/epoch - 6ms/step
Epoch 38/50
53/53 - 0s - loss: 0.5980 - sparse_categorical_accuracy: 0.7983 - 349ms/epoch - 7ms/step
Epoch 39/50
53/53 - 0s - loss: 0.5942 - sparse_categorical_accuracy: 0.8017 - 330ms/epoch - 6ms/step
Epoch 40/50
53/53 - 0s - loss: 0.5921 - sparse_categorical_accuracy: 0.8016 - 330ms/epoch - 6ms/step
Epoch 41/50
53/53 - 0s - loss: 0.5900 - sparse_categorical_accuracy: 0.8006 - 342ms/epoch - 6ms/step
Epoch 42/50
53/53 - 0s - loss: 0.5922 - sparse_categorical_accuracy: 0.7998 - 324ms/epoch - 6ms/step
Epoch 43/50
53/53 - 0s - loss: 0.5902 - sparse_categorical_accuracy: 0.8028 - 335ms/epoch - 6ms/step
Epoch 44/50
53/53 - 0s - loss: 0.5888 - sparse_categorical_accuracy: 0.8015 - 347ms/epoch - 7ms/step
Epoch 45/50
53/53 - 0s - loss: 0.5883 - sparse_categorical_accuracy: 0.8034 - 318ms/epoch - 6ms/step
Epoch 46/50
53/53 - 0s - loss: 0.5897 - sparse_categorical_accuracy: 0.8020 - 331ms/epoch - 6ms/step
Epoch 47/50
53/53 - 0s - loss: 0.5875 - sparse_categorical_accuracy: 0.8012 - 335ms/epoch - 6ms/step
Epoch 48/50
53/53 - 0s - loss: 0.5875 - sparse_categorical_accuracy: 0.8010 - 324ms/epoch - 6ms/step
Epoch 49/50
53/53 - 0s - loss: 0.5881 - sparse_categorical_accuracy: 0.8015 - 327ms/epoch - 6ms/step
Epoch 50/50
53/53 - 0s - loss: 0.5885 - sparse_categorical_accuracy: 0.8011 - 329ms/epoch - 6ms/step

# Evaluate Transfer Learning Model

In [33]:
k, accuracies,fscores, precisions, recalls = [],[],[],[],[]
for i in range(max_case_length):
    test_data_subset = test_df[test_df["k"]==i]
    if len(test_data_subset) > 0:
        test_token_x, test_token_y, token_x2 = prepare_data_next_activity(test_data_subset, 
            x_word_dict, y_word_dict, x2_word_dict, max_case_length)   
        y_pred = np.argmax(transformer_resource_embedding_and_transfer_learning_model.predict([test_token_x, token_x2]), axis=1)
        accuracy = metrics.accuracy_score(test_token_y, y_pred)
        precision, recall, fscore, _ = metrics.precision_recall_fscore_support(
            test_token_y, y_pred, average="weighted")
        k.append(i)
        accuracies.append(accuracy)
        fscores.append(fscore)
        precisions.append(precision)
        recalls.append(recall)

k.append(i + 1)
accuracies.append(np.mean(accuracy))
fscores.append(np.mean(fscores))
precisions.append(np.mean(precisions))
recalls.append(np.mean(recalls))
print('Average accuracy across all prefixes:', np.mean(accuracies))
print('Average f-score across all prefixes:', np.mean(fscores))
print('Average precision across all prefixes:', np.mean(precisions))
print('Average recall across all prefixes:', np.mean(recalls))

Average accuracy across all prefixes: 0.8623245527683729
Average f-score across all prefixes: 0.822333851524708
Average precision across all prefixes: 0.8345986379500994
Average recall across all prefixes: 0.850851598832404